apiVersion: v1
kind: Service
metadata:
  name: nodejs-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"3001":"nodejs-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: nodejs-sample
  ports:
    - name: http
      port: 3001
      protocol: TCP
      targetPort: 3000
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nodejs-backendconfig
spec:
  securityPolicy:
    name: "security-policy"
  timeoutSec: 30
  logging:
    enable: true
    sampleRate: 1.0
  cdn:
    enabled: false
  sessionAffinity: 
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 300
  
  # In many cases, healthCheck section should be matched with the Pod's Readiness Probe.
  healthCheck: 
    type: HTTP
    requestPath: /healthz # MUST return 200OK
    port: 3000 # Container Port. NOT Service Port
    checkIntervalSec: 5
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 2